services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    image: ${ECR_REPO:-django-lambda-app}:latest
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - DB_NAME=django_db
      - DB_USER=django_user
      - DB_PASSWORD=django_password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SECRET_KEY=test
      - DJANGO_DEBUG=TRUE
    command: python manage.py runserver 0.0.0.0:8080
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
